/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'veraxmedax' at '11/3/16 8:45 PM' with Gradle 3.0
 *
 * @author veraxmedax, @date 11/3/16 8:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
